config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'confirm'
      get 'bought'
    end
    resources :comments, only: [:create,:destroy, :edit, :update]
  end
  resources :users, only: [:show] do
    collection do
      get 'purchase_item'
      get 'sell_item'
      get 'comment_item'
    end
    member do
      get 'personal_infomation', to: 'users#personal_infomation',
      controllers: {
        personal_infomation: 'users/personal_infomation'
      }
      get 'logout', to: 'users#logout'
    end
  end
  resources :credit_cards, only: [:index, :new, :show] do
    collection do
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
      post 'show', to: 'credit_cards#show'
    end
  end
  resources :item_sell, only: :new
  resources :addresses, only: [:edit, :update]

  # resources :categories, only: [:index] do
  #   member do
  #     get 'parent'
  #     get 'child'
  #     get 'grandchild'
  #   end
  # end

end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  
  require "payjp"
  before_action :card_exists?, only:[:index]
  before_action :set_categorys
  
  def index
  end

  def new
    card = CreditCard.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      )
      @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def show
    card = CreditCard.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def delete
    card = CreditCard.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "index"
  end

  def card_exists?
    @card = CreditCard.where(user_id: current_user.id).first if CreditCard.where(user_id: current_user.id).present?
    if @card.present?
      redirect_to action: "show"
    end
  end

  private
  def set_categorys
    @categories = Category.all  
  end

end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/index.html.haml
= render partial: "template/header"
= render partial: "template/sellbtn"

- breadcrumb :mypage_card
= render 'template/breadcrumbs'

.user-showPage
  .user-showPage__main
    = render "users/side_bar"

    .main-information
      .main-information__payTop
        %h2 支払い方法
      .main-information__payMiddle
        %p クレジットカード一覧
        .main-information__payMiddle__credit-AdditionBtn
          = icon("far", "credit-card")
          = link_to "クレジットカードを追加する", new_credit_card_path, method: :get

= render partial: "template/banner"
= render partial: "template/footer"

app/views/credit_cards/new.html.haml
= render partial: "template/header"
= render partial: "template/sellbtn"
- breadcrumb :register_card
= render 'template/breadcrumbs'

.creditCard-wrapper
  .creditCard-wrapper__inner
    .creditCard-wrapper__inner__title
      %h1 クレジットカード情報入力

    .creditCard-wrapper__inner__form
      = form_with model: @card, url: pay_credit_cards_path, method: :post, id: "card-form", local: true do |f|
        .creditCard-wrapper__inner__form__card-number
          %label カード番号
          %span.essential-redBox 必須
          %br
          = f.text_field :card_number, type: "text", class: "cardNumber-input", id: "card-number", placeholder: "半角数字のみ", maxlength: "16"

        .creditCard-wrapper__inner__form__dayLimit
          %label 有効期限
          %span.essential-redBox 必須
          %br
          = f.select :exp_month, [["01",1], ["02",2], ["03",3], ["04",4], ["05",5], ["06",6], ["07",7], ["08",8], ["09",9], ["10",10], ["11",11], ["12",12]], {}, class: 'dateSelect', id: 'card-month'
          月

          = f.select :exp_year, [["20",2020], ["21",2021], ["22",2022], ["23",2023], ["24",2024], ["25",2025], ["26",2026], ["27",2027], ["28",2028], ["29",2029]], {}, class: 'dateSelect', id: 'card-year'
          年

        .creditCard-wrapper__inner__form__security-code
          %label セキュリティーコード
          %span.essential-redBox 必須
          %br
          = f.text_field :cvc, type: 'text', class: 'security-input', id: 'card-cvc', placeholder: "カード背面4ケタor3ケタの番号", maxlength: "4"

        .creditCard-wrapper__inner__form__addBtn
          =f.submit "クレジットカードを登録する", id: "token_submit", class: "card-btn"
        
= render partial: "template/banner"
= render partial: "template/footer"

app/views/credit_cards/show.html.haml
= render partial: "template/header"
= render partial: "template/sellbtn"

- breadcrumb :mypage_card
= render 'template/breadcrumbs'

.user-showPage
  .user-showPage__main
    = render "users/side_bar"

    .main-information
      .main-information__cardsIndex-inner
        .main-information__cardsIndex-inner__title
          %h1 クレジットカード一覧

        .main-information__cardsIndex-inner__contents
          .main-information__cardsIndex-inner__contents__creditCard-information
            .main-information__cardsIndex-inner__contents__creditCard-information__number
              %p
              = "**** **** ****" + @default_card_information.last4
            .main-information__cardsIndex-inner__contents__creditCard-information__date
              %p
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              = exp_month + "/" + exp_year
          .main-information__cardsIndex-inner__contents__deleteBtn
            = form_tag(delete_credit_cards_path, method: :post) do
              %input{ type: "hidden", name: "credit-card_id", value: "" }
              %button.card-deleteBtn 削除する

= render partial: "template/banner"
= render partial: "template/footer"