config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'confirm'
      get 'bought'
    end
    resources :comments, only: [:create,:destroy, :edit, :update]
  end
  resources :users, only: [:show] do
    collection do
      get 'purchase_item'
      get 'sell_item'
      get 'comment_item'
    end
    member do
      get 'personal_infomation', to: 'users#personal_infomation',
      controllers: {
        personal_infomation: 'users/personal_infomation'
      }
      get 'logout', to: 'users#logout'
    end
  end
  resources :credit_cards, only: [:index, :new, :show] do
    collection do
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
      post 'show', to: 'credit_cards#show'
    end
  end
  resources :item_sell, only: :new
  resources :addresses, only: [:edit, :update]

  # resources :categories, only: [:index] do
  #   member do
  #     get 'parent'
  #     get 'child'
  #     get 'grandchild'
  #   end
  # end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  validates :nickname,
    presence: true
  validates :email,
    format: { with: /\A[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*\z/},
    presence: true
  validates :first_name,
    format: { with: /\A([ぁ-んァ-ン一-龥]|ー)+\z/},
    presence: true
  validates :last_name,
    format: { with: /\A([ぁ-んァ-ン一-龥]|ー)+\z/},
    presence: true
  validates :first_name_kana,
    format: { with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/},
    presence: true
  validates :last_name_kana,
    format: { with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/},
    presence: true
  validates :birthday,
    presence: true
  has_one :address


  has_many :comments

  has_one :credit_card, dependent: :destroy
  has_many :items

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  def failure
    redirect_to root_path
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted? #ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
    else #ユーザー情報が未登録なので、新規登録画面へ遷移する
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  before_action :set_categorys

  def new
    @user = User.new
  end

  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
  end

  def edit
    super
  end

  def update
    super
  end


  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  private
  
  def set_categorys
    @categories = Category.all  
  end

  # def user_params
  #   params.require(:user).permit(:nickname, :first_name, :last_name, :first_name_kana, :last_name_kana, :birthday)
  # end

  protected
  
  def address_params
    params.require(:address).permit(:destination_first_name, :destination_last_name, :destination_first_name_kana, :destination_last_name_kana, :postal_code, :prefecture_id, :city, :block, :building, :phone_numeber)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_categorys

  def show
    @nickname = current_user.nickname
    @items = Item.where(seller_id: current_user.id) 
  end

  def edit
    @user = User.find(params[:id])
  end

  def personal_infomation
    @user = User.find(params[:id])
    @address = Address.find(params[:id])
  end

  def purchase_item
    @items = Item.where(buyer_id: current_user.id).page(params[:page]).per(7)
  end

  def sell_item
    @items = Item.where(seller_id: current_user.id).page(params[:page]).per(7)
  end

  def comment_item
    @comments = Comment.where(user_id: current_user.id).select(:item_id).distinct.page(params[:page]).per(7)
  end


  private
  def set_categorys
    @categories = Category.all  
  end

  
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_main_bar.html.haml
.main-information
  -if current_page?(user_path)
    .main-information__showMypage-contents1
      .main-information__showMypage-contents1__left
        .main-information__showMypage-contents1__left__profile-image
          = image_tag('no-image.png')

      .main-information__showMypage-contents1__right
        .main-information__showMypage-contents1__right__upper
          %h2
            = @nickname
        .main-information__showMypage-contents1__right__lower
          -# .main-information__showMypage-contents1__right__lower__review
            -# %ul.showMypage-review-itemsBox
            -#   %li 評価
            -#   %li 4.0
          .main-information__showMypage-contents1__right__lower__items
            %ul.showMypage-review-itemsBox
              %li 出品数
              %li 
                = @items.length
  = link_to edit_user_registration_path do
    .nickname_change
      ニックネームを変更する

app/views/users/_side_bar.html.haml
.sideBar-Wrapper
  .sideBar-Top
    %ul.sideBar-contents
      %li
        = link_to "マイページ", "/users/#{current_user.id}"
      -# %li
      -#   = link_to "いいね！した商品", root_path
      -# %li
      -#   = link_to "ブックマークした商品", root_path
      -# %li
      -#   = link_to "最近チェックした商品", root_path
      %li
        = link_to "コメントした商品",comment_item_users_path
      -# %li
      -#   = link_to "下書きした商品", root_path
      %li
        = link_to "商品を出品する",new_item_path
      %li
        = link_to "出品した商品",sell_item_users_path
      %li
        = link_to "購入した商品",purchase_item_users_path
      -# %li
      -#   = link_to "お知らせ", root_path

  .sideBar-Low
    %h2 設定
    %ul.sideBar-contents
      %li
        = link_to "プロフィール", root_path
      %li
        = link_to "住所変更",edit_address_path(current_user.id)
      %li
        = link_to "メール/パスワード変更", edit_user_registration_path
      %li
        = link_to "支払い方法", controller: 'credit_cards'
      %li
        = link_to "登録されている個人情報", personal_infomation_user_path(current_user.id)
      %li
        = link_to "ログアウト", logout_user_path(current_user.id)

app/views/users/comment_item.html.haml
= render partial: "template/header"
= render partial: "template/sellbtn"
- breadcrumb :comment
= render 'template/breadcrumbs'

.user-showPage
  .user-showPage__main
    = render "side_bar"
    .user_show-item
      .item__info
        .item__info__area
          %p.item__info__area--title
            コメントした商品
            - @comments.each do |comment|
              - last_comment = Comment.order(created_at: :desc).find_by(item_id: comment.item.id)
              .item__info__area__box
                = link_to "",item_path(comment.item.id),class:"purchase_link"
                - image = Image.find_by(item_id: comment.item.id)
                .item__info__area__box__picture
                  = image_tag image.src_url, alt: 'サブ画像', height: '78px', width: '80px'
                %p.item__info__area__box__item_name
                  =comment.item.name
                  に対してコメントしています。
                  最終コメントは
                  =  last_comment.created_at.strftime("%Y年%m月%d日 %H:%M")
                  になります。
                %p.item__info__area__box__item_btn
                  >
          
        = paginate @comments


= render partial: "template/banner"
= render partial: "template/footer"

app/views/users/logout.html.haml
= render partial: "template/header"
= render partial: "template/sellbtn"

- breadcrumb :mypage_logout
= render 'template/breadcrumbs'

.user-showPage
  .user-showPage__main
    = render "side_bar"
    
    .main-information
      -if current_page?(logout_user_path)
        .main-information__logout-btn
          = link_to "ログアウト", destroy_user_session_path, method: :delete

= render partial: "template/banner"
= render partial: "template/footer"

app/views/users/personal_infomation.html.haml
= render partial: "template/header"
= render partial: "template/sellbtn"

- breadcrumb :mypage_personal_information
= render 'template/breadcrumbs'

.mypage__personal_infomation
  .mypage__side_bar
    = render "side_bar"
  .personal_infomation
    %h1.title
      登録されている個人情報
    %p.suggestion
      送付先の住所を変更したい場合は、
      %br/
      下の「変更する」ボタンより変更をお願いします
    .content
      %span
        お名前
      .name
        .name__last
          = @user.last_name
        .name__first
          = @user.first_name
    .content
      %span
        お名前カナ
      .name
        .name__last
          = @user.last_name_kana
        .name__first
          = @user.first_name_kana
    .content
      %span
        生年月日
      .birthday
        = @user.birthday
    .destination
      送付先の住所
    .content
      %span
        送付先の住所の名前
      .name
        .name__last
          = @address.destination_last_name
        .name__first
          = @address.destination_first_name
    .content
      %span
        送付先の住所の名前(カナ)
      .name
        .name__last
          = @address.destination_last_name_kana
        .name__first
          = @address.destination_first_name_kana
    .content
      %span
        郵便番号
      .postal_code_number
        = @address.postal_code
    .content
      %span
        都道府県
      .prefcture__name
        = @address.prefecture.name
    .content
      %span
        市区町村
      .city_name
        = @address.city
    .content
      %span
        番地
      .block__name
        = @address.block
    .content
      %span
        建物名
      .building__name
        = @address.building
    .content
      %span
        電話番号
      .phone_number
        = @address.phone_numeber
    = link_to edit_address_path(current_user.id), class: "link-btn" do
      .link-btn
        変更する

= render partial: "template/banner"
= render partial: "template/footer"

app/views/users/purchase_item.html.haml
= render partial: "template/header"
= render partial: "template/sellbtn"
- breadcrumb :purchase_items
= render 'template/breadcrumbs'

.user-showPage
  .user-showPage__main
    = render "side_bar"
    .user_show-item
      .item__info
        .item__info__area
          %p.item__info__area--title
            購入した商品
            - @items.each do |item|
              .item__info__area__box
                = link_to "",item_path(item.id),class:"purchase_link"
                - image = Image.find_by(item_id: item.id)
                .item__info__area__box__picture
                  = image_tag image.src_url, alt: 'サブ画像', height: '78px', width: '80px'
                %p.item__info__area__box__item_name
                  =item.name
                  を購入しました。
                %p.item__info__area__box__item_btn
                  >
          
        = paginate @items


= render partial: "template/banner"
= render partial: "template/footer"

app/views/users/sell_item.html.haml
= render partial: "template/header"
= render partial: "template/sellbtn"
- breadcrumb :sell_item_lists
= render 'template/breadcrumbs'

.user-showPage
  .user-showPage__main
    = render "side_bar"
    .user_show-item
      .item__info
        .item__info__area
          %p.item__info__area--title
            出品したの商品
            - @items.each do |item|
              .item__info__area__box
                = link_to "",item_path(item.id),class:"purchase_link"
                - image = Image.find_by(item_id: item.id)
                .item__info__area__box__picture
                  = image_tag image.src_url, alt: 'サブ画像', height: '78px', width: '80px'
                %p.item__info__area__box__item_name
                  =item.name
                  を出品中です。
                  -if item.buyer_id.present?
                    - buyer = User.find(item.buyer_id)
                    %span
                      =buyer.nickname
                      さんが商品を購入しました。
                %p.item__info__area__box__item_btn
                  >
          
        = paginate @items


= render partial: "template/banner"
= render partial: "template/footer"

app/views/users/show.html.haml
= render partial: "template/header"
= render partial: "template/sellbtn"

- breadcrumb :mypage
= render 'template/breadcrumbs'

.user-showPage
  .user-showPage__main
    = render "side_bar"
    = render "main_bar"

= render partial: "template/banner"
= render partial: "template/footer"