config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'confirm'
      get 'bought'
    end
    resources :comments, only: [:create,:destroy, :edit, :update]
  end
  resources :users, only: [:show] do
    collection do
      get 'purchase_item'
      get 'sell_item'
      get 'comment_item'
    end
    member do
      get 'personal_infomation', to: 'users#personal_infomation',
      controllers: {
        personal_infomation: 'users/personal_infomation'
      }
      get 'logout', to: 'users#logout'
    end
  end
  resources :credit_cards, only: [:index, :new, :show] do
    collection do
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
      post 'show', to: 'credit_cards#show'
    end
  end
  resources :item_sell, only: :new
  resources :addresses, only: [:edit, :update]

  # resources :categories, only: [:index] do
  #   member do
  #     get 'parent'
  #     get 'child'
  #     get 'grandchild'
  #   end
  # end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :seller, class_name: "User"
  has_many :images, dependent: :destroy
  belongs_to :category
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  validates_associated :images
  
  validates  :name, :explain, :category_id, :state_id, :shipping_burden_id, :prefecture_id, :shipping_day_id,:price, :seller_id,:images, presence: true
  validates :name, length: { maximum: 40 }
  validates :explain, length: { maximum: 1000 }
  validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :state
  belongs_to_active_hash :shipping_burden
  belongs_to_active_hash :shipping_day
  belongs_to_active_hash :prefecture


  def previous
    Item.where("id < ?", self.id).order("id DESC").first
  end

  def next
    Item.where("id > ?", self.id).order("id ASC").first
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  require "payjp"
  before_action :set_item, except: [:index, :new, :create, :get_category_children, :get_category_grandchildren]
  before_action :move_to_index, only:[:new,:create,:edit,:update,:confirm ]
  before_action :move_to_index_for_soldout, only: [:edit,:confirm,:bought]
  before_action :move_to_index_for_notseller, only: [:edit,:update]
  before_action :move_to_index_for_seller, only: [:confirm]
  before_action :set_category, only: [:parent, :child, :grandchild]
  #header用
  before_action :set_categorys, only: [:index, :show, :confirm]
  before_action :set_card, only: [:confirm, :bought]


  def index
    @items = Item.includes(:seller).order("created_at DESC").limit(4)
    @categories = Category.all
  end
  
  def new
    if user_signed_in?
    @item = Item.new
    @item.images.new
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    @category_parent_array.unshift("---")
    else
      flash[:alert] = '出品するには、ログインするか新規会員登録をしてください。'
      redirect_to root_path
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.valid?
      @item.save
      flash[:notice] = '出品が完了しました'
      redirect_to root_path
    else
      @category_parent_array = Category.where(ancestry: nil).pluck(:name)
      @category_parent_array.unshift("---")
      flash.now[:alert] = '必須項目を入力してください'
      @item = Item.new(item_params)
      @item.images.new
      render :new
    end
  end

  def edit
    edit_category
  end

  def update
    if item_params[:images_attributes].nil?
      flash.now[:alert] = '更新失敗しました。画像を登録してください。'
      edit_category
      render :edit
    else
      exit_ids = []
      item_params[:images_attributes].each do |a,b|
        exit_ids << item_params[:images_attributes].dig(:"#{a}",:id).to_i
      end
      ids = Image.where(item_id: params[:id]).map{|image| image.id }
      delete__db = ids - exit_ids
      Image.where(id:delete__db).destroy_all
      @item.touch
      if @item.update(item_params)
        flash[:notice] = '更新が完了しました'
        redirect_to item_path(@item.id)
      else
        set_item
        edit_category
        flash.now[:alert] = '更新できませんでした。必須項目を入力してください。'
        render :edit
      end
    end
  end


  def show
    @item = Item.find(params[:id])
    @seller = User.find(@item.seller_id)
    @comment = Comment.new
    @items = Item.where(category: @item.category_id).where.not(id: @item.id).order(created_at: :desc).limit(3)
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :show
    end 
  end

  def confirm
    @image = Image.find_by(item_id: params[:id])
    @user = User.find(current_user.id)
    if @card
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def bought
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    customer = Payjp::Customer.retrieve(@card.customer_id)
    charge = Payjp::Charge.create(
      amount: @item.price,
      customer: Payjp::Customer.retrieve(@card.customer_id),
      currency: 'jpy'
    )
    @item_buyer = Item.find(params[:id])
    @item_buyer.update(buyer_id: current_user.id)
  end

  def get_category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end
  
  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end



  def edit_category
    grandchild_category = @item.category
    child_category = grandchild_category.parent

    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    @category_children_array =  Category.where(ancestry: child_category.ancestry)
    @category_grandchildren_array =  Category.where(ancestry: grandchild_category.ancestry)

  end

  private

  def item_params
    params.require(:item).permit(:name, :explain, :brand, :state_id, :shipping_burden_id, :prefecture_id, :category_id, :shipping_day_id, :price, images_attributes:[:src, :_destroy, :id]).merge(seller_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_categorys
    @categories = Category.all  
  end
  
  def set_card
    @card = CreditCard.find_by(user_id: current_user.id)
  end


  def move_to_index_for_soldout
    item = Item.find(params[:id])
    redirect_to action: :index if item.buyer_id.present?
  end

  def move_to_index_for_notseller
    item = Item.find(params[:id])
    redirect_to action: :index unless item.seller_id == current_user.id
  end
  def move_to_index_for_seller
    item = Item.find(params[:id])
    redirect_to action: :index if item.seller_id== current_user.id
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_items_list.html.haml
- @items.each do |item|
  = link_to item_path(item) do
    .pickup__list__img
      = image_tag(item.images.first.src.url)
        - if item.buyer_id.present?
        .pickup__list__img__soldBox
          .pickup__list__img__soldBox--soldOut
            SOLD
    .pickup__list__body
      = item.name
      .details
        %ul
          %li
            = "¥ #{item.price.to_s(:delimited)}"
          -# %li.likeicon
          -#   %i.fa.fa-star
          -#     1
        %p (税込)

app/views/items/_sell_footer.html.haml
.footer
  %ul.lists
    %li.list
      %a{ href: "#" } プライバシーポリシー
    %li.list
      %a{ href: "#" } フリマ利用規約
    %li.list
      %a{ href: "#" } 特定商取引に関する表記
  .footer__icon
    = link_to '#' do
      = image_tag "logo-white.png",{class:"box-icon", width: "80px",height: "65x"}
      %p fleamaketSample74a
    

app/views/items/_sell_header.html.haml
.sell_header
  = link_to image_tag(src= "logo.png", class: "header_icon"), root_path

app/views/items/_sell_main.html.haml
.sell_main
  .box
    =form_with model:@item ,class:"item_new__box",local: true do |form|
      - if @item.errors.any?
        %ul.error_message_items_new
          - @item.errors.full_messages.each do |message|
            %li.error_message_items_new__li
              = message
      .phots 
        .phots__names
          .phots__names--label
            出品画像
          .phots__names--important
            必須
        .phots__explan
          最大10枚までアップロードできます

        .phots_posts_container
          .prev-content
            .preview-box
              - if @item.persisted?
                - @item.images.each_with_index do |image,i|
                  .image-box__content{data: { index: i }}
                    = image_tag image.src.url, width: "118px;", height: '118px;'
                    .js-remove 削除
              .upper-box
                .prev-img-data-upper
                .label-upper-content-0
                  %label{for: "item_images_attributes_0_src", class: "label-box", id: "label-box--0"}
                    %pre.label-box__text-visible クリックしてファイルをアップロード
 
              .lower-box
                .prev-img-data-lower
                .label-lower-content-4
                  %label{for: "item_images_attributes_4_src", class: "label-box", id: "label-box--1"}
                    %pre.label-box__text-visible クリックしてファイルをアップロード

              .hidden-content
                = form.fields_for :images do |image|
                  .js-file_group{"data-index": "#{image.index}"}
                    = image.file_field :src, accept: "image/*", class: "js-file", data: {index: image.index}, id: "item_images_attributes_#{image.index}_src"

                  - if @item.persisted?
                    = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'

                - if @item.persisted?
                  .js-file_group{"data-index": "#{@item.images.count}"}
                    = file_field_tag :src, name: "item[images_attributes][#{@item.images.count}][src]", class: 'js-file'
      .items
        .items__names
          .items__names--label
            商品名
          .items__names--important
            必須
        = form.text_field :name,autocomplete: "off", placeholder:"40文字まで", class:"input_form"
        .items__explans
          .items__explans__explan
            .items__explans__explan--label
              商品の説明
            .items__explans__explan--importamt
              必須
          = form.text_area :explain, rows: "7", class:"items_explan_text-box", :autocomplete => "off", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）&#13;&#10;&#13;&#10;例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。".html_safe 
        .form_count
          %span.items--count
          %span.items--count--max  /1000
      .category
        %p 商品の詳細
        .category__names
          .category__names--label 
            カテゴリー
          .category__names--important
            必須
        .listing-form-box
          .listing-select-wrapper
            .listing-select-wrapper__box
              = form.select :category_id, @category_parent_array, {}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
        .brand__names
          .brand__names--label
            ブランド
          .brand__names--optional
            任意
        .brand__textfields
          .brand__textfield
            = form.text_field :brand,autocomplete: "off", placeholder:"例）シャネル", class:"input_form"     
        .brand__status__names
          .brand__status__names--label 
            商品の状態
          .brand__status__names--important
            必須
        .status__select
          .status__selectarea
            = form.collection_select :state_id, State.all, :id, :name, prompt: "---", class: 'select_state'
      .shipping
        .shipping__words
          .shipping__words--word
            配送について
          .shipping__words--question__mark{"aria-hidden" => "true", :class => "question__mark", :fill => "#222222", "fill-rule" => "evenodd", :viewbox => "0 0 24 24"}
            ?
        .shipping__payer 
          .shipping__payer--label
            配送料の負担
          .shipping__payer--important
            必須
        .payer__select
          .payer__selectarea
            = form.collection_select :shipping_burden_id, ShippingBurden.all, :id, :name, prompt: "---", class: 'select_shipping_burden'
        .shipping__from__area
          .shipping__from__area--label
            発送元の地域
          .shipping__from__area--important
            必須
        .from__area__select
          .from__area__select--area
            = form.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "---", class: 'select_prefecture'
        .shipping__day
          .shipping__day--label 
            発送までの日数
          .shipping__day--important 
            必須
        .days  
          .days_selectarea
            = form.collection_select :shipping_day_id, ShippingDay.all, :id, :name, prompt: "---", class: 'select_shipping_day'
      .price
        .price__scorps   
          .price__scorps--scorp
            価格（¥300〜9,999,999）
          .price__scorps--question_mark
            ?      
        .price__prices
          .price__prices__names
            .price__prices__names--label
              販売価格
            .price__prices__names--important
              必須
          .price__prices__form__price
            .price__prices__form__price__input_area
              .price__prices__form__price__input_area--yen_mark 
                ¥
              = form.number_field :price,prautocomplete: "off", class: "form_price", min:"300", max:"9999999",placeholder:"300"
        .price__sales_commission
          .price__sales_commission__fees
            .price__sales_commission__fees__fee
              .price__sales_commission__fees__fee--label
                販売手数料（10%）
            .price__sales_commission--fees_mark
              —
        .price__sales_profit
          .price__sales_profit__gains
            .price__sales_profit__gains__gain
              .price__sales_profit__gains__gain--label
                販売利益
            .price__sales_profit__gains__gain--mark
              —
        .price__sales_bottons
          = form.submit "出品する", class:"sales_btn"
          %button.save_btn{:tabindex => "0", :type => "button"} 
            下書きに保存
          %a.back{:href => "/"} 
            もどる
        .price__matter
          禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

app/views/items/bought.html.haml
.items-boght
  .items-boght__header
    %h1.logo
      = link_to root_path do
        = image_tag 'furima.svg'
  %h2.items-boght__done 商品を購入しました
  = link_to "トップページへ戻る", root_path, class: "items_bought--btn"

app/views/items/confirm.html.haml
= render 'template/header'
- breadcrumb :item_confirm
= render 'template/breadcrumbs'

.comfirm_wrapper
  .comfirm_main 
    %h2.comfirm_main--head
      購入内容の確認
    .comfirm_main__item
      .comfirm_main__item__left
        = image_tag (@item.images.first.src.url), alt: 'img画像',  height: '100px', width: '100px', class: 'comfirm_main__item__left--img'
      .comfirm_main__item__right
        %h6.comfirm_main__item__right__title
          =@item.name
        .comfirm_main__item__right__lower
          %p.comfirm_main__item__right__lower--detail
            = @item.shipping_burden.name
          %p.comfirm_main__item__right__lower--price
            ¥
            = @item.price 
    .comfirm_main__price
      %h3.comfirm_main__price__left
        支払い金額
      %p.comfirm_main__price__right
        ¥
        = @item.price 
    .comfirm_main__payment
      .comfirm_main__payment__head
        %h3.comfirm_main__payment__head--left
          支払い方法
        =link_to "変更する >", credit_cards_path, class:"comfirm_main__payment__head--right"
      .comfirm_main__payment--card_info
        - if @card.present?
          %p.comfirm_main__payment--card_info__type
            クレジットカード
          %p.comfirm_main__payment--card_info__num
            = "**** **** ****" + @default_card_information.last4
          %p.comfirm_main__payment--card_info__date
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + "/" + exp_year
        - else
          クレジットカードを登録してください
    .comfirm_main__address
      .comfirm_main__address__hedder
        %h3.comfirm_main__address__hedder__left
          配送先
        = link_to "変更する >" ,edit_address_path(current_user.id, item_id: @item.id), class:"comfirm_main__address__hedder__right" 
      %ul.comfirm_main__address__area
        %li.comfirm_main__address__area--number
          = @user.address.postal_code
        %li.comfirm_main__address__area--main
          = @user.address.prefecture.name
          = @user.address.city
          = @user.address.block
          = @user.address.building
        %li.comfirm_main__address__area--name
          = @user.address.destination_last_name
          =" "
          = @user.address.destination_first_name

    .comfirm_main__buy
      -if @card.nil?
        = link_to "支払い登録" , new_credit_card_path, method: :get, class:"comfirm_main__buy--btn"
      -else
        = link_to "購入する" , bought_item_path, method: :get, class:"comfirm_main__buy--btn"
      = link_to "戻る" , "/items/#{@item.id}", class:"comfirm_main__buy--back_btn"
      
= render 'sell_footer'

app/views/items/index.html.haml
= render partial: "template/header"
= render partial: "template/sellbtn"

.top-main
  %section.firstView
    .firstView__content
      %h2.firstView__content__copy
        %br 人生を変えるフリマアプリ
      %p.firstView__content__text 
        FURIMAはだれでもかんたんに出品・購入できる
        %br フリマアプリです
      .firstView__content__btn
        = link_to '#' do
          .applebtn
            = image_tag 'app-store.svg'
        = link_to '#' do
          .googlebtn
            = image_tag 'google-play.svg'
  %section.introduction
    %h2.introduction__title 
      FURIMAが選ばれる3つの理由
      .introduction__sub
    %ul.lists
      %li.list
        .list__img
          %span.number 1
          = image_tag "pict-reason-01.jpg"
        %h3.list__sub
          %span 3分
          ですぐに出品
        %p.list__explanation
          スマホで入力するだけで簡単に出品できる！
      %li.list
        .list__img
          %span.number 2
          = image_tag "pict-reason-02.jpg"
        %h3.list__sub
          %span シンプル
          で使いやすい
        %p.list__explanation
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list
        .list__img
          %span.number 3
          = image_tag "pict-reason-03.jpg"
        %h3.list__sub
          手数料
          %span 業界最安
        %p.list__explanation
          最大3%でお得に出品&購入！
  %section.middleBanner
    .middleBanner__content
      %h2.middleBanner__content__title
        会員数日本一位
      %p.middleBanner__content__text
        FURIMAは、フリマアプリで最も人気。
        %br 出品・購入回数も業界最多です！
        %br ほしかったあの商品に出会えるかもしれません。
      .middleBanner__content__btn
        = link_to '#' do
          .applebtn
            = image_tag "app-store.svg"
        = link_to '#' do
          .googlebtn
            = image_tag "google-play.svg"
  %section.features
    %h2.features__title
      FURIMAの特徴
      .features__sub
    %ul.lists
      %li.list
        .list__img
          = image_tag "icon-01.png"
        %h3.list__sub
          簡単に売り買いできる
        %p.list__explanation
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %li.list
        .list__img
          = image_tag "icon-03.png"
        %h3.list__sub
          売上金は即日振込みに対応 
        %p.list__explanation
          午前9時までに振込を依頼頂ければ、翌日に指定の口座に入金いたします！
      %li.list
        .list__img
          = image_tag "icon-04.png"
        %h3.list__sub
          様々な支払いに対応
        %p.list__explanation
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  %section.pickup
    %h2.pickup__title
      ピックアップカテゴリー
    .pickup__box
      .pickup__head
        = link_to '#' do
          %h3.pickup__title
            新規投稿商品
      .pickup__lists
        = render partial: 'items_list'
        
  %section.pickup
    %h2.pickup__title
      ピックアップブランド
    .pickup__box
      .pickup__head
        = link_to '#' do
          %h3.pickup__title
            アーカイバ
      .pickup__lists
        = render partial: 'items_list'

= render partial: "template/banner"
= render partial: "template/footer"

app/views/items/new.html.haml
= render "sell_header"
- breadcrumb :items_new
= render 'template/breadcrumbs'

= render "sell_main"
= render partial: "template/banner"
= render partial: "template/footer"

app/views/items/sell_confirm.html.haml
%header.login-page-header
  =link_to root_path do
    .header-logo
      = image_tag 'logo.png'
.sell_confirm
  .sell_confirm__main
    %h2.sell_confirm__main--head
      出品内容の確認
    .sell_comfirm__main__item
      .sell_comfirm__main__item__left
        = image_tag "IMG_main.jpg", alt: 'img画像',  height: '100px', width: '100px', class: 'comfirm_main__item__left--img'
      .sell_comfirm__main__item__right
        %h6.sell_comfirm__main__item__right__title
          出品する商品の名前
        .sell_comfirm__main__item__right__lower
          %p.comfirm__main__item__right__lower--detail
            商品の説明
    .sell_comfirm__main__category
      %h3.sell_comfirm__main__category__name
        カテゴリー
    .sell_comfirm__main__brand
      %h3.sell_comfirm__main__brand__name
        ブランド
    .sell_comfirm__main__status
      %h3.sell_comfirm__main__status
        商品の状態
    %ul.sell_comfirm__main__price
      %li.sell_comfirm__main__price__amount
        商品の販売価格
        ¥10000
      %li.sell_comfirm__main__price__fee
        販売手数料(10%)
      %li.sell_comfirm__main__price__gain
        販売利益
    .sell_comfirm__main__shipping
      .sell_comfirm__main__shipping__headder
        %h3.sell_comfirm__main__shipping__headder__left
          発送元の地域
        = link_to "変更する >" ,"#", class:"comfirm_main__address__hedder__right"
      %ul.sell_comfirm__main__shipping__list
        %li.sell_comfirm__main__shipping__list--payer
          配送料の負担
        %li.sell_comfirm__main__shipping__list--shippingdays
          発送までの日数
    .sell_comfirm__main__sell
      = link_to "出品する" ,"#", class:"comfirm__main__sell--btn"
      = link_to "戻る" , "#", class:"comfirm__main__sell--back_btn"
%footer.login-page-footer
  %ul.footer-links
    %li
      =link_to "プライバシーポリシー", root_path
    %li
      =link_to "利用契約", root_path
    %li
      =link_to "特定取引に関する表記"
  =link_to root_path do
    .footer-logo
      =image_tag 'logo-white.png'
  %p
    ©a班 

app/views/items/show.html.haml
= render 'template/header'
- breadcrumb :item_show
= render 'template/breadcrumbs'

.item_show-wrapper
  = render 'template/sellbtn'
  .item_show-wrapper__main
    .item_show-wrapper__main__img
      %h2.item_show-wrapper__main__img-title
        = @item.name
      .item_show-wrapper__main__img--area
        - if @item.buyer_id.present?
          .item_show-wrapper__main__img--area--solad
            %h2.solad-title
              SOLD
        .item_show-wrapper__main__img--area--main
          = image_tag @item.images[0].src_url, alt: 'メイン画像', height: '350px', width: '560px',id:"MainPhoto"
      %ul.item_show-wrapper__main__img-sub 
        - @item.images.each do |image|
          %li.item_show-wrapper__main__img-sub--photo
            = image_tag image.src_url, alt: 'サブ画像', height: '90px', width: '100px',class:"ChangePhoto"
      %p.item_show-wrapper__main__img-price
        ¥ 
        = @item.price 
        
        %p.item_show-wrapper__main__img-price-detail
          = @item.shipping_burden.name
        %p.item_show-wrapper__main__img-price-text
          = @item.explain
    .item_show-wrapper__main__teble
      %table.item_show-wrapper__main__teble__date
        %tr  
          %th  
            出品者
          %td
            = @seller.nickname
        %tr  
          %th 
            カテゴリー
          %td
            .category
              = @item.category.parent.parent.name
            .category
              = @item.category.parent.name
            .category
              = @item.category.name
        %tr  
          %th 
            ブランド
          %td
            = @item.brand
        %tr  
          %th 
            商品の状態
          %td
            = @item.state.name
        %tr  
          %th 
            配送料の負担
          %td
            = @item.shipping_burden.name
        %tr  
          %th  
            発送元の地域
          %td
            = @item.prefecture.name
        %tr  
          %th
            発送日の目安
          %td
            = @item.shipping_day.name
    -# .item_show-wrapper__main__optionalArea
    -#   .item_show-wrapper__main__optionalArea_like
    -#     = icon('fas', 'star')
    -#     お気に入り 1
    -#   .item_show-wrapper__main__optionalArea_report
    -#     = icon('fa', 'flag')
    -#     = link_to "不適切な商品の通報","#"
    
    - if @item.buyer_id.present?
      %p.item_buy_out 売り切れ
    - else
      - if user_signed_in? && current_user.id == @seller.id 
        .item_show-wrapper__main__buy
          .item_show-wrapper__main__seller
            .item_show-wrapper__main__seller__edit
              = link_to "編集する",edit_item_path(@item.id),class:"item_show-wrapper__main__seller__edit--btn"
            .item_show-wrapper__main__seller__delete
              = link_to "出品を取り消す", item_path(@item.id), method: :delete ,class:"item_show-wrapper__main__seller__delete--btn"
      - elsif user_signed_in?
        = link_to "購入画面に進む",confirm_item_path(@item.id),class:"item_show-wrapper__main__buy--btn"
      - else
        = link_to "ログイン画面へ",new_user_session_path ,class:"item_show-wrapper__main__login--btn"

  .item_show-wrapper__comment
    .item_show-wrapper__comment_area
      - if @item.comments
        - @item.comments.each do |comment|
          .item_show-wrapper__comment_area--data
            .item_show-wrapper__comment_area--data__user_name
              %span.item_show-wrapper__comment_area--data__user_name-box
                = comment.user.nickname
                -if user_signed_in? && comment.user_id == @seller.id 
                  %span (出品者)
              -if user_signed_in? && current_user.id == comment.user.id
                .comment__current_user--btn
                  = link_to "編集する", "/items/#{@item.id}/comments/#{comment.id}/edit" ,class:"comment__current_user--btn--edit"
                  = link_to "削除する","/items/#{@item.id}/comments/#{comment.id}",class:"comment__current_user--btn--delet", method: :delete
            .item_show-wrapper__comment_area--data_box
              %p.item_show-wrapper__comment_area--data_box__text
                = comment.text
              .item_show-wrapper__comment_area--data_box__time
                = comment.created_at.strftime("%Y-%m-%d %H:%M")

    .item_show-wrapper__comment_box
      -if @item.buyer_id.nil?
        - if user_signed_in? 
          = render "comments/form"
        - else
          %p.item_show-wrapper__comment_box--not_signed
            ※コメント機能は
            %span.rogin_link
              =link_to "ログイン", new_user_session_path
            %span
              するとできるようになります
      - else

  .item_show-wrapper__itemLinks
    .item_show-wrapper__itemLinks__before
      - if @item.previous.present?
        = link_to icon('fa','angle-left'),"#"
        = link_to "前の商品", item_path(@item.previous.id)
      - else

    .item_show-wrapper__itemLinks__affter
      -if @item.next.present?
        = link_to "後ろの商品", item_path(@item.next.id)
        = link_to icon('fa','angle-right'),"#"





  .item_show-wrapper__relatedItems
    .item_show-wrapper__relatedItems__category_name
      = link_to "#{@item.category.parent.parent.name}  #{@item.category.parent.name}  #{@item.category.name}  をもっと見る","#"
    
    
      .item_show-wrapper__relatedItems__list
        -@items.each do |item|
          .item_show-wrapper__relatedItems__list__box
            =link_to "" ,"/items/#{item.id}"
            .item_show-wrapper__relatedItems__list__box_img
              = image_tag item.images[0].src_url, alt: 'image', height: '150px', width: '220px'
            .item_show-wrapper__relatedItems__list__box_main
              %h6.item_show-wrapper__relatedItems__list__box_main--title
                = item.name
                %ul.item_show-wrapper__relatedItems__list__box_main--data
                  %li
                    ￥
                    = item.price
                %p= item.shipping_burden.name
      
= render partial: "template/footer"